# Generated by Django 2.1a1 on 2018-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
        ('profiles', '0002_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='favourited_by', to='articles.Article'),
        ),
    ]
